VALID_PHONE = ""
VALID_PASSWORD = ""
VALID_EMAIL = ""

INVALID_PHONE = "0000000000"
INVALID_EMAIL = "invalid@invalid.invalid"
INVALID_PASSWORD = "InvalidPass123"
SHORT_PASSWORD = "Qw1"
MISMATCH_PASSWORD = "Mismatch123"